### ISSUE TITLE
home/distanced API doesn't return any results in production

### ISSUE THREAD

**Issue by techstalgist** [timoh/craftbeer#22]
Go to https://getbeer.herokuapp.com/home/distanced?lat=60.17964980000001&lng=24.9254007

-> you get an error. Investigate Rails server production.log?

**Comment by timoh** [comment]
This is the log, need to investigate further:

```
2016-07-04T16:35:44.379809+00:00 app[web.1]: Processing by HomeController#all_with_distance as */*
2016-07-04T16:35:44.398378+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.find | STARTED | {"find"=>"alco_avails", "filter"=>{"alco_drink_id"=>BSON::ObjectId('57796e46bdc8560003503e32')}}
2016-07-04T16:35:44.390019+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.find | STARTED | {"find"=>"reviews", "filter"=>{"alco_drink_id"=>BSON::ObjectId('57796e46bdc8560003503e32')}, "limit"=>-1}
2016-07-04T16:35:44.391547+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.find | SUCCEEDED | 0.001459806s
2016-07-04T16:35:44.393299+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.aggregate | STARTED | {"aggregate"=>"alco_avails", "pipeline"=>[{"$match"=>{"alco_drink_id"=>BSON::ObjectId('57796e46bdc8560003503e32')}}, {"$match"=>{"alco_drink_id"=>BSON::ObjectId('57796e46bdc8560003503e32'), "amount"=>{"$exists"=>true}}}, {"$group"=>{"_id"=>"amount", "...
2016-07-04T16:35:44.397687+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.aggregate | SUCCEEDED | 0.0043042010000000006s
2016-07-04T16:35:44.402959+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.find | STARTED | {"find"=>"alco_locations", "filter"=>{"_id"=>BSON::ObjectId('57796e4cbdc8560003504003')}, "limit"=>-1}
2016-07-04T16:35:44.405622+00:00 app[web.1]:   app/models/alco_drink.rb:168:in `block in all_with_distance'
2016-07-04T16:35:44.405622+00:00 app[web.1]:   app/models/alco_drink.rb:172:in `block (2 levels) in all_with_distance'
2016-07-04T16:35:44.404661+00:00 app[web.1]: Completed 500 Internal Server Error in 25ms
2016-07-04T16:35:44.402080+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.find | SUCCEEDED | 0.003637963s
2016-07-04T16:35:44.405597+00:00 app[web.1]:
2016-07-04T16:35:44.405620+00:00 app[web.1]: NoMethodError (undefined method `[]' for nil:NilClass):
2016-07-04T16:35:44.405621+00:00 app[web.1]:   app/models/alco_location.rb:31:in `get_distance_to_point'
2016-07-04T16:35:44.403702+00:00 app[web.1]: MONGODB | ds011735-a.mlab.com:11735 | heroku_krsdtn25.find | SUCCEEDED | 0.000684777s
2016-07-04T16:35:44.405624+00:00 app[web.1]:
2016-07-04T16:35:44.405623+00:00 app[web.1]:   app/models/alco_drink.rb:158:in `all_with_distance'
2016-07-04T16:35:44.405623+00:00 app[web.1]:   app/controllers/home_controller.rb:13:in `all_with_distance'
2016-07-04T16:35:44.405624+00:00 app[web.1]:
```

**Comment by timoh** [comment]
@techstalgist seems to be working now.

**Comment by techstalgist** [comment]
This seems to work now.
